[package]
name = "rhymr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_12"] }
sourceview5 = { version = "0.9.1", features = ["gtk_v4_12"] }
glib = "0.20.7"
tokio = { version = "1.42.0", features = ["full"] }
datamuse-api-rs = "2.1.0"
futures-channel = "0.3"
futures-util = "0.3.31"
gio = "0.20.7"
grass = "0.13.4"

[build-dependencies]
glib-build-tools = "0.20.0"
